In [4]:
import pandas as pd
import os

In [16]:
crime_2020_df = pd.read_excel("data/NIBRSPublicView.Jan1-Dec31-2020.xlsx")

In [17]:
crime_2021_df = pd.read_excel("data/NIBRSPublicViewSep21.xlsx")

In [19]:
#Clean up the headers 2020
crime_2020_df = crime_2020_df.rename(columns = {  "Occurrence\nDate": "Date", 
                                                  "Occurrence\nHour": "Hour",
                                                  "NIBRS\nClass": "NIBRS_Class",
                                                  "NIBRSDescription": "Offense_Type",
                                                  "Offense\nCount": "Offense_Count",
                                                  "Block Range": "Street_No",
                                                  "StreetName": "Street_Name",
                                                  "Street\nType": "Street_Type",
                                                  "ZIP Code": "Zip_Code"
                                               }
                                    )
    
crime_2020_df.head() 

crime_2020_df

,Incident,Date,Hour,NIBRS_Class,Offense_Type,Offense_Count,Beat,Premise,Street_No,Street_Name,Street_Type,Suffix,City,Zip_Code
0,79220,2020-01-01,0,120,Robbery,1,12D60,"Residence, Home (Includes Apartment)",16302,EL CAMINO REAL,NaN,NaN,HOUSTON,77062
1,59342520,2020-01-01,0,220,"Burglary, Breaking and Entering",1,14D40,"Residence, Home (Includes Apartment)",12000,MARTIN LUTHER KING,BLVD,NaN,HOUSTON,77048
2,123324720,2020-01-01,0,220,"Burglary, Breaking and Entering",1,4F10,Restaurant,9440,KATY,FWY,NaN,HOUSTON,77055
3,233120,2020-01-01,0,240,Motor vehicle theft,1,16E30,"Parking Lot, Garage",14711,MAIN,ST,NaN,HOUSTON,77085
4,240920,2020-01-01,0,240,Motor vehicle theft,1,20G30,"Residence, Home (Includes Apartment)",3030,SHADOWBRIAR,DR,NaN,HOUSTON,77082
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247906,174530420,2020-12-31,23,90C,Disorderly conduct,1,19G50,"Residence, Home (Includes Apartment)",10350,LANDS END,DR,NaN,HOUSTON,77099
247907,174520620,2020-12-31,23,90D,Driving under the influence,1,2A10,"Highway, Road, Street, Alley",1600,CAVALCADE,ST,NaN,HOUSTON,77009
247908,356121,2020-12-31,23,90Z,All other offenses,1,5F30,"Residence, Home (Includes Apartment)",6000,HOLLISTER,ST,NaN,HOUSTON,77040
247909,174508320,2020-12-31,23,90Z,All other offenses,1,22B20,"Residence, Home (Includes Apartment)",1100,LANGWICK,DR,NaN,HOUSTON,77060
247910,174518620,2020-12-31,23,90Z,All other offenses,1,3B40,"Residence, Home (Includes Apartment)",802,40TH,ST,E,HOUSTON,77022

In [20]:
#Clean up the headers 2021
crime_2021_df = crime_2021_df.rename(columns = {  "RMSOccurrenceDate": "Date", 
                                                  "RMSOccurrenceHour": "Hour",
                                                  "NIBRSClass": "NIBRS_Class",
                                                  "NIBRSDescription": "Offense_Type",
                                                  "OffenseCount": "Offense_Count",
                                                  "StreetNo": "Street_No",
                                                  "StreetName": "Street_Name",
                                                  "StreetType": "Street_Type",
                                                  "ZIPCode": "Zip_Code"
                                               }
                                    )
    
crime_2021_df.head() 

crime_2021_df

,Incident,Date,Hour,NIBRS_Class,Offense_Type,Offense_Count,Beat,Premise,Street_No,Street_Name,Street_Type,Suffix,City,Zip_Code
0,1621,2021-01-01,0,13A,Aggravated Assault,1,18F40,"Residence, Home (Includes Apartment)",8787,WOODWAY,DR,NaN,HOUSTON,77063
1,1621,2021-01-01,0,13B,Simple assault,1,18F40,"Residence, Home (Includes Apartment)",8787,WOODWAY,DR,NaN,HOUSTON,77063
2,8821,2021-01-01,0,35A,"Drug, narcotic violations",1,19G30,"Highway, Road, Street, Alley",13339,VERBENA,LN,NaN,HOUSTON,77083
3,8821,2021-01-01,0,23F,Theft from motor vehicle,1,19G30,"Highway, Road, Street, Alley",13339,VERBENA,LN,NaN,HOUSTON,77083
4,11721,2021-01-01,0,90C,Disorderly conduct,1,12D10,"Residence, Home (Includes Apartment)",8839,BARTON,ST,NaN,HOUSTON,77075
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
183771,133031021,2021-09-30,23,290,"Destruction, damage, vandalism",1,7C10,"Residence, Home (Includes Apartment)",4417,NICHOLS,ST,NaN,HOUSTON,77020
183772,133300021,2021-09-30,23,290,"Destruction, damage, vandalism",1,19G10,"Parking Lot, Garage",10630,BEECHNUT,ST,NaN,HOUSTON,77072
183773,133300021,2021-09-30,23,23F,Theft from motor vehicle,1,19G10,"Parking Lot, Garage",10630,BEECHNUT,ST,NaN,HOUSTON,77072
183774,134942021,2021-09-30,23,290,"Destruction, damage, vandalism",1,15E30,"Residence, Home (Includes Apartment)",7171,BUFFALO SPEEDWAY,NaN,NaN,HOUSTON,77025
183775,136362221,2021-09-30,23,240,Motor vehicle theft,1,22B20,"Residence, Home (Includes Apartment)",400,GREENS,RD,NaN,HOUSTON,77060

In [21]:
#Check Headers
crime_2020_df.columns

Index(['Incident', 'Date', 'Hour', 'NIBRS_Class', 'Offense_Type',
       'Offense_Count', 'Beat', 'Premise', 'Street_No', 'Street_Name',
       'Street_Type', 'Suffix', 'City', 'Zip_Code'],
      dtype='object')

In [22]:
#Check Headers
crime_2021_df.columns

Index(['Incident', 'Date', 'Hour', 'NIBRS_Class', 'Offense_Type',
       'Offense_Count', 'Beat', 'Premise', 'Street_No', 'Street_Name',
       'Street_Type', 'Suffix', 'City', 'Zip_Code'],
      dtype='object')

In [23]:
#Concatenate data frames 
data_frames = [crime_2020_df, crime_2021_df]
crime_df = pd.concat(data_frames, sort=False)
crime_df

,Incident,Date,Hour,NIBRS_Class,Offense_Type,Offense_Count,Beat,Premise,Street_No,Street_Name,Street_Type,Suffix,City,Zip_Code
0,79220,2020-01-01,0,120,Robbery,1,12D60,"Residence, Home (Includes Apartment)",16302,EL CAMINO REAL,NaN,NaN,HOUSTON,77062
1,59342520,2020-01-01,0,220,"Burglary, Breaking and Entering",1,14D40,"Residence, Home (Includes Apartment)",12000,MARTIN LUTHER KING,BLVD,NaN,HOUSTON,77048
2,123324720,2020-01-01,0,220,"Burglary, Breaking and Entering",1,4F10,Restaurant,9440,KATY,FWY,NaN,HOUSTON,77055
3,233120,2020-01-01,0,240,Motor vehicle theft,1,16E30,"Parking Lot, Garage",14711,MAIN,ST,NaN,HOUSTON,77085
4,240920,2020-01-01,0,240,Motor vehicle theft,1,20G30,"Residence, Home (Includes Apartment)",3030,SHADOWBRIAR,DR,NaN,HOUSTON,77082
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
183771,133031021,2021-09-30,23,290,"Destruction, damage, vandalism",1,7C10,"Residence, Home (Includes Apartment)",4417,NICHOLS,ST,NaN,HOUSTON,77020
183772,133300021,2021-09-30,23,290,"Destruction, damage, vandalism",1,19G10,"Parking Lot, Garage",10630,BEECHNUT,ST,NaN,HOUSTON,77072
183773,133300021,2021-09-30,23,23F,Theft from motor vehicle,1,19G10,"Parking Lot, Garage",10630,BEECHNUT,ST,NaN,HOUSTON,77072
183774,134942021,2021-09-30,23,290,"Destruction, damage, vandalism",1,15E30,"Residence, Home (Includes Apartment)",7171,BUFFALO SPEEDWAY,NaN,NaN,HOUSTON,77025
183775,136362221,2021-09-30,23,240,Motor vehicle theft,1,22B20,"Residence, Home (Includes Apartment)",400,GREENS,RD,NaN,HOUSTON,77060

In [24]:
#Makes an output directory
dir = r"Output"
if not os.path.exists(dir):
    os.mkdir(dir)

In [25]:
crime_df.to_csv('Output/1_crime_data_merged.csv', index=False)