In [2]:
import csv 
import json
import pandas as pd
def  read_csv(path):
    return pd.read_csv(path, thousands=',')

In [3]:
df =read_csv('6_Cleaned_lat_long.csv')
df1= read_csv('5_Population_Data.csv')

In [4]:
df_inc =df.groupby('Zip_Code')['Incident'].count().reset_index()

In [5]:
dfg =df.groupby(['Zip_Code','Latitude','Longitude'])['Incident'].count().to_frame().reset_index()

In [6]:
dfj = pd.merge(df1,dfg, how='inner', on = 'Zip_Code')
dfj.dropna().to_json('joineddata.json',orient='records')

In [7]:
data = json.load(open('Zip_Codes.geojson'))

df = pd.DataFrame(data)
df

                  type                                           features
0    FeatureCollection  {'type': 'Feature', 'properties': {'FID': 1, '...
1    FeatureCollection  {'type': 'Feature', 'properties': {'FID': 2, '...
2    FeatureCollection  {'type': 'Feature', 'properties': {'FID': 3, '...
3    FeatureCollection  {'type': 'Feature', 'properties': {'FID': 4, '...
4    FeatureCollection  {'type': 'Feature', 'properties': {'FID': 5, '...
..                 ...                                                ...
208  FeatureCollection  {'type': 'Feature', 'properties': {'FID': 209,...
209  FeatureCollection  {'type': 'Feature', 'properties': {'FID': 210,...
210  FeatureCollection  {'type': 'Feature', 'properties': {'FID': 211,...
211  FeatureCollection  {'type': 'Feature', 'properties': {'FID': 212,...
212  FeatureCollection  {'type': 'Feature', 'properties': {'FID': 213,...

[213 rows x 2 columns]

In [8]:
df4 =pd.json_normalize(data['features'], max_level=2)
df4

,type,properties.FID,properties.OBJECTID_1,properties.ZIP_CODE,properties.Shape__Area,properties.Shape__Length,geometry.type,geometry.coordinates
0,Feature,1,1,77371,1.244441e+09,223749.362712,Polygon,"[[[-95.0040769457526, 30.5801463687412], [-94...."
1,Feature,2,2,77331,3.045327e+08,130259.009143,Polygon,"[[[-95.0099099399588, 30.6280163963206], [-95...."
2,Feature,3,3,77358,1.497502e+08,71529.419671,Polygon,"[[[-95.3590400369784, 30.5044673548145], [-95...."
3,Feature,4,4,77378,3.752378e+08,121150.753751,Polygon,"[[[-95.4858580622215, 30.3849553256113], [-95...."
4,Feature,5,5,77868,1.101315e+09,210542.360669,Polygon,"[[[-95.8711481644514, 30.241756282708], [-95.9..."
...,...,...,...,...,...,...,...,...
208,Feature,209,209,77048,3.873736e+07,28967.889007,Polygon,"[[[-95.2977647320424, 29.5966940845128], [-95...."
209,Feature,210,210,77053,2.509866e+07,24896.081126,Polygon,"[[[-95.4923350308938, 29.5804891496837], [-95...."
210,Feature,211,211,77515,6.706386e+08,175527.496564,Polygon,"[[[-95.5605070238541, 29.2515380803459], [-95...."
211,Feature,212,212,77377,1.429633e+08,76348.236073,Polygon,"[[[-95.7811587485695, 30.0627280389046], [-95...."
212,Feature,213,213,77433,2.060194e+08,80968.913972,Polygon,"[[[-95.8078330193023, 29.9283947619024], [-95...."

In [9]:
df4 =pd.json_normalize(data['features'], max_level=1)
hhh= df4.rename(columns={"properties.FID": "FID", "properties.OBJECTID_1": "OBJECTID_1","properties.ZIP_CODE": "ZIP_CODE", "properties.Shape__Area": "Shape__Area", "properties.Shape__Length": "Shape__Length", "geometry.type": "gtype", "geometry.coordinates": "coordinates"})

In [10]:
df5= df4.rename(columns={"properties.FID": "FID", "properties.OBJECTID_1": "properties.OBJECTID_1","properties.ZIP_CODE": "Zip_Code", "properties.Shape__Area": "Shape__Area", "properties.Shape__Length": "Shape__Length", "geometry.type": "gtype", "geometry.coordinates": "coordinates"})
dfjr =  pd.merge(df1,df5, how='inner', on = 'Zip_Code')
dfjr_ince_j =  pd.merge(df_inc,dfjr, how='inner', on = 'Zip_Code')
dfjr_ince_j

,Zip_Code,Incident,Population,Population Density,Housing Units,Median Home Value,Occupied_Housing_Units,Median_Household_Income,Gender_Male,Gender_Female,...,Full_Time,Part_Time,Unemployed,type,FID,properties.OBJECTID_1,Shape__Area,Shape__Length,gtype,coordinates
0,77002,5952,16793,8320,3757,"$208,600",3080,"$64,093",13839,2954,...,3349,3939,4151,Feature,70,70,7.149421e+06,21907.529332,Polygon,"[[[-95.3609299978651, 29.752328185498], [-95.3..."
1,77003,2821,10508,4144,4713,"$162,600",3894,"$36,412",5709,4799,...,3685,2024,2726,Feature,72,72,9.807752e+06,19933.927314,Polygon,"[[[-95.3609299978651, 29.752328185498], [-95.3..."
2,77004,6989,32692,5660,16618,"$191,700",12802,"$41,983",16368,16324,...,9054,8505,10288,Feature,83,83,1.912479e+07,20088.893542,Polygon,"[[[-95.3421650065287, 29.7320181967403], [-95...."
3,77005,1117,25528,6639,10299,"$754,000",9548,"$159,732",12528,13000,...,9332,5216,5861,Feature,86,86,1.158540e+07,18137.760238,Polygon,"[[[-95.3906940088399, 29.7238511886229], [-95...."
4,77006,4813,19664,8720,13602,"$327,300",11809,"$67,458",11111,8553,...,10918,4854,3371,Feature,78,78,7.844795e+06,13087.389392,Polygon,"[[[-95.4021100145369, 29.7256851885587], [-95...."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137,77583,1,28531,171,7366,"$137,800",6654,"$68,939",17417,11114,...,7908,3235,11922,Feature,208,208,6.906035e+08,180149.239554,Polygon,"[[[-95.5921680349589, 29.3262970909591], [-95...."
138,77584,14,70228,2188,25184,"$189,600",23722,"$94,103",34146,36082,...,30294,10681,12593,Feature,207,207,1.181611e+08,60401.735054,Polygon,"[[[-95.4337157255136, 29.5440774692765], [-95...."
139,77586,7,20970,1615,9487,"$190,100",8304,"$86,786",10628,10342,...,8373,3828,4815,Feature,139,139,4.982592e+07,44555.729955,Polygon,"[[[-94.9882408922733, 29.6088851748795], [-94...."
140,77587,47,16568,5581,5156,"$77,900",4691,"$36,083",8370,8198,...,4821,2826,4025,Feature,112,112,1.044635e+07,14216.836015,Polygon,"[[[-95.2492429786405, 29.6521651722426], [-95...."
141,77598,394,23059,1905,11956,"$117,100",10615,"$46,682",11550,11509,...,9637,4584,3922,Feature,118,118,4.850466e+07,47868.428482,Polygon,"[[[-95.1611449403993, 29.4970861587462], [-95...."

In [11]:
li = []
from collections import OrderedDict
for index, row in dfjr_ince_j.iterrows():
    d=OrderedDict()
    d['type']='Feature'
    d['properties']={'Zip_Code': row['Zip_Code'],'PopulationDensity':  row['Population Density'],'Incident':row['Incident'],'Population': row['Population'],'Gender_Male':row['Gender_Male'],'Gender_Female':row['Gender_Female'],'Unemployed':row['Unemployed'],'Shape__Area':row['Shape__Area'],'Shape__Length':row['Shape__Length']}
    d['geometry']={'type': 'Polygon','coordinates': [row['coordinates']]}
    li.append(d)
d = OrderedDict()
d['type']='FeatureCollection'
d['features']=li
with open('GeoObs_NE.json', 'w') as f:
    f.write(json.dumps(d, sort_keys=False, indent=0))

In [12]:
dj =hhh.to_json(orient='records')
# dj