In [1]:
import os 
import pandas as pd
from datetime import datetime

# #Crime_DF  SQL cleanup

In [81]:
crime_df = pd.read_csv("../Output/4_crime_data_lat_long_tract.csv")

crime_df

,Incident,Date,Hour,NIBRS_Class,Offense_Type,Offense_Grouped,Offense_Count,Beat,Premise,Street_No,Street_Name,Street_Type,City,State,Zip_Code,Full_Address,Street_Address,Latitude,Longitude,Census_Tract
0,79220,2020-01-01,0,120,Robbery,Burglary/Robbery,1,12D60,"Residence, Home (Includes Apartment)",16302.0,EL CAMINO REAL,NaN,Houston,TX,77062,"16302 EL CAMINO REAL , Houston, TX",16302+EL+CAMINO+REAL+,29.560020,-95.125244,340701.0
1,59342520,2020-01-01,0,220,"Burglary, Breaking and Entering",Burglary/Robbery,1,14D40,"Residence, Home (Includes Apartment)",12000.0,MARTIN LUTHER KING,BLVD,Houston,TX,77048,"12000 MARTIN LUTHER KING BLVD, Houston, TX",12000+MARTIN+LUTHER+KING+BLVD,NaN,NaN,331604.0
2,123324720,2020-01-01,0,220,"Burglary, Breaking and Entering",Burglary/Robbery,1,4F10,Restaurant,9440.0,KATY,FWY,Houston,TX,77055,"9440 KATY FWY, Houston, TX",9440+KATY+FWY,29.785149,-95.531461,522301.0
3,233120,2020-01-01,0,240,Motor vehicle theft,Theft,1,16E30,"Parking Lot, Garage",14711.0,MAIN,ST,Houston,TX,77085,"14711 MAIN ST, Houston, TX",14711+MAIN+ST,29.676383,-95.428505,NaN
4,240920,2020-01-01,0,240,Motor vehicle theft,Theft,1,20G30,"Residence, Home (Includes Apartment)",3030.0,SHADOWBRIAR,DR,Houston,TX,77082,"3030 SHADOWBRIAR DR, Houston, TX",3030+SHADOWBRIAR+DR,29.731948,-95.599466,452002.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
354130,133031021,2021-09-30,23,290,"Destruction, damage, vandalism",Vandalism,1,7C10,"Residence, Home (Includes Apartment)",4417.0,NICHOLS,ST,Houston,TX,77020,"4417 NICHOLS ST, Houston, TX",4417+NICHOLS+ST,29.781080,-95.326351,211301.0
354131,133300021,2021-09-30,23,290,"Destruction, damage, vandalism",Vandalism,1,19G10,"Parking Lot, Garage",10630.0,BEECHNUT,ST,Houston,TX,77072,"10630 BEECHNUT ST, Houston, TX",10630+BEECHNUT+ST,29.689024,-95.604058,453100.0
354132,133300021,2021-09-30,23,23F,Theft from motor vehicle,Theft,1,19G10,"Parking Lot, Garage",10630.0,BEECHNUT,ST,Houston,TX,77072,"10630 BEECHNUT ST, Houston, TX",10630+BEECHNUT+ST,29.689024,-95.604058,453100.0
354133,134942021,2021-09-30,23,290,"Destruction, damage, vandalism",Vandalism,1,15E30,"Residence, Home (Includes Apartment)",7171.0,BUFFALO SPEEDWAY,NaN,Houston,TX,77025,"7171 BUFFALO SPEEDWAY , Houston, TX",7171+BUFFALO+SPEEDWAY+,29.702431,-95.427477,413203.0
354134,136362221,2021-09-30,23,240,Motor vehicle theft,Theft,1,22B20,"Residence, Home (Includes Apartment)",400.0,GREENS,RD,Houston,TX,77060,"400 GREENS RD, Houston, TX",400+GREENS+RD,29.950418,-95.406558,240102.0

In [77]:
crime_df[['Street_No', 'Latitude','Longitude','Census_Tract']] = crime_df[['Street_No', 'Latitude','Longitude','Census_Tract']].fillna(0) 
crime_df.dtypes

Incident             int64
Date                object
Hour                 int64
NIBRS_Class         object
Offense_Type        object
Offense_Grouped     object
Offense_Count        int64
Beat                object
Premise             object
Street_No          float64
Street_Name         object
Street_Type         object
City                object
State               object
Zip_Code             int64
Full_Address        object
Street_Address      object
Latitude           float64
Longitude          float64
Census_Tract       float64
dtype: object

In [82]:
crime_df

,Incident,Date,Hour,NIBRS_Class,Offense_Type,Offense_Grouped,Offense_Count,Beat,Premise,Street_No,Street_Name,Street_Type,City,State,Zip_Code,Full_Address,Street_Address,Latitude,Longitude,Census_Tract
0,79220,2020-01-01,0,120,Robbery,Burglary/Robbery,1,12D60,"Residence, Home (Includes Apartment)",16302.0,EL CAMINO REAL,NaN,Houston,TX,77062,"16302 EL CAMINO REAL , Houston, TX",16302+EL+CAMINO+REAL+,29.560020,-95.125244,340701.0
1,59342520,2020-01-01,0,220,"Burglary, Breaking and Entering",Burglary/Robbery,1,14D40,"Residence, Home (Includes Apartment)",12000.0,MARTIN LUTHER KING,BLVD,Houston,TX,77048,"12000 MARTIN LUTHER KING BLVD, Houston, TX",12000+MARTIN+LUTHER+KING+BLVD,NaN,NaN,331604.0
2,123324720,2020-01-01,0,220,"Burglary, Breaking and Entering",Burglary/Robbery,1,4F10,Restaurant,9440.0,KATY,FWY,Houston,TX,77055,"9440 KATY FWY, Houston, TX",9440+KATY+FWY,29.785149,-95.531461,522301.0
3,233120,2020-01-01,0,240,Motor vehicle theft,Theft,1,16E30,"Parking Lot, Garage",14711.0,MAIN,ST,Houston,TX,77085,"14711 MAIN ST, Houston, TX",14711+MAIN+ST,29.676383,-95.428505,NaN
4,240920,2020-01-01,0,240,Motor vehicle theft,Theft,1,20G30,"Residence, Home (Includes Apartment)",3030.0,SHADOWBRIAR,DR,Houston,TX,77082,"3030 SHADOWBRIAR DR, Houston, TX",3030+SHADOWBRIAR+DR,29.731948,-95.599466,452002.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
354130,133031021,2021-09-30,23,290,"Destruction, damage, vandalism",Vandalism,1,7C10,"Residence, Home (Includes Apartment)",4417.0,NICHOLS,ST,Houston,TX,77020,"4417 NICHOLS ST, Houston, TX",4417+NICHOLS+ST,29.781080,-95.326351,211301.0
354131,133300021,2021-09-30,23,290,"Destruction, damage, vandalism",Vandalism,1,19G10,"Parking Lot, Garage",10630.0,BEECHNUT,ST,Houston,TX,77072,"10630 BEECHNUT ST, Houston, TX",10630+BEECHNUT+ST,29.689024,-95.604058,453100.0
354132,133300021,2021-09-30,23,23F,Theft from motor vehicle,Theft,1,19G10,"Parking Lot, Garage",10630.0,BEECHNUT,ST,Houston,TX,77072,"10630 BEECHNUT ST, Houston, TX",10630+BEECHNUT+ST,29.689024,-95.604058,453100.0
354133,134942021,2021-09-30,23,290,"Destruction, damage, vandalism",Vandalism,1,15E30,"Residence, Home (Includes Apartment)",7171.0,BUFFALO SPEEDWAY,NaN,Houston,TX,77025,"7171 BUFFALO SPEEDWAY , Houston, TX",7171+BUFFALO+SPEEDWAY+,29.702431,-95.427477,413203.0
354134,136362221,2021-09-30,23,240,Motor vehicle theft,Theft,1,22B20,"Residence, Home (Includes Apartment)",400.0,GREENS,RD,Houston,TX,77060,"400 GREENS RD, Houston, TX",400+GREENS+RD,29.950418,-95.406558,240102.0

In [83]:
crime_df['Street_No'] = crime_df['Street_No'].replace('.0', '', regex=True)
crime_df

,Incident,Date,Hour,NIBRS_Class,Offense_Type,Offense_Grouped,Offense_Count,Beat,Premise,Street_No,Street_Name,Street_Type,City,State,Zip_Code,Full_Address,Street_Address,Latitude,Longitude,Census_Tract
0,79220,2020-01-01,0,120,Robbery,Burglary/Robbery,1,12D60,"Residence, Home (Includes Apartment)",16302.0,EL CAMINO REAL,NaN,Houston,TX,77062,"16302 EL CAMINO REAL , Houston, TX",16302+EL+CAMINO+REAL+,29.560020,-95.125244,340701.0
1,59342520,2020-01-01,0,220,"Burglary, Breaking and Entering",Burglary/Robbery,1,14D40,"Residence, Home (Includes Apartment)",12000.0,MARTIN LUTHER KING,BLVD,Houston,TX,77048,"12000 MARTIN LUTHER KING BLVD, Houston, TX",12000+MARTIN+LUTHER+KING+BLVD,NaN,NaN,331604.0
2,123324720,2020-01-01,0,220,"Burglary, Breaking and Entering",Burglary/Robbery,1,4F10,Restaurant,9440.0,KATY,FWY,Houston,TX,77055,"9440 KATY FWY, Houston, TX",9440+KATY+FWY,29.785149,-95.531461,522301.0
3,233120,2020-01-01,0,240,Motor vehicle theft,Theft,1,16E30,"Parking Lot, Garage",14711.0,MAIN,ST,Houston,TX,77085,"14711 MAIN ST, Houston, TX",14711+MAIN+ST,29.676383,-95.428505,NaN
4,240920,2020-01-01,0,240,Motor vehicle theft,Theft,1,20G30,"Residence, Home (Includes Apartment)",3030.0,SHADOWBRIAR,DR,Houston,TX,77082,"3030 SHADOWBRIAR DR, Houston, TX",3030+SHADOWBRIAR+DR,29.731948,-95.599466,452002.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
354130,133031021,2021-09-30,23,290,"Destruction, damage, vandalism",Vandalism,1,7C10,"Residence, Home (Includes Apartment)",4417.0,NICHOLS,ST,Houston,TX,77020,"4417 NICHOLS ST, Houston, TX",4417+NICHOLS+ST,29.781080,-95.326351,211301.0
354131,133300021,2021-09-30,23,290,"Destruction, damage, vandalism",Vandalism,1,19G10,"Parking Lot, Garage",10630.0,BEECHNUT,ST,Houston,TX,77072,"10630 BEECHNUT ST, Houston, TX",10630+BEECHNUT+ST,29.689024,-95.604058,453100.0
354132,133300021,2021-09-30,23,23F,Theft from motor vehicle,Theft,1,19G10,"Parking Lot, Garage",10630.0,BEECHNUT,ST,Houston,TX,77072,"10630 BEECHNUT ST, Houston, TX",10630+BEECHNUT+ST,29.689024,-95.604058,453100.0
354133,134942021,2021-09-30,23,290,"Destruction, damage, vandalism",Vandalism,1,15E30,"Residence, Home (Includes Apartment)",7171.0,BUFFALO SPEEDWAY,NaN,Houston,TX,77025,"7171 BUFFALO SPEEDWAY , Houston, TX",7171+BUFFALO+SPEEDWAY+,29.702431,-95.427477,413203.0
354134,136362221,2021-09-30,23,240,Motor vehicle theft,Theft,1,22B20,"Residence, Home (Includes Apartment)",400.0,GREENS,RD,Houston,TX,77060,"400 GREENS RD, Houston, TX",400+GREENS+RD,29.950418,-95.406558,240102.0

In [85]:
#Convert Datatypes
crime_df['Incident'] = crime_df['Incident'].astype('string')
crime_df['Date'] = pd.to_datetime(crime_df['Date'])
crime_df['NIBRS_Class'] = crime_df['NIBRS_Class'].astype('string')
crime_df['Offense_Type'] = crime_df['Offense_Type'].astype('string')
crime_df['Offense_Grouped'] = crime_df['Offense_Grouped'].astype('string')
crime_df['Beat'] = crime_df['Beat'].astype('string')
crime_df['Premise'] = crime_df['Premise'].astype('string')
crime_df['Street_No'] = crime_df['Street_No'].astype('string')
crime_df['Street_Name'] = crime_df['Street_Name'].astype('string')
crime_df['Street_Type'] = crime_df['Street_Type'].astype('string')

crime_df['City'] = crime_df['City'].astype('string')
crime_df['State'] = crime_df['State'].astype('string')
crime_df['Full_Address'] = crime_df['Full_Address'].astype('string')
crime_df['Street_Address'] = crime_df['Street_Address'].astype('string')
crime_df['Census_Tract'] = crime_df['Census_Tract'].astype('string')

crime_df.dtypes

Incident                   string
Date               datetime64[ns]
Hour                        int64
NIBRS_Class                string
Offense_Type               string
Offense_Grouped            string
Offense_Count               int64
Beat                       string
Premise                    string
Street_No                  string
Street_Name                string
Street_Type                string
City                       string
State                      string
Zip_Code                    int64
Full_Address               string
Street_Address             string
Latitude                  float64
Longitude                 float64
Census_Tract               string
dtype: object

,Incident,Date,Hour,NIBRS_Class,Offense_Type,Offense_Grouped,Offense_Count,Beat,Premise,Street_No,Street_Name,Street_Type,City,State,Zip_Code,Full_Address,Street_Address,Latitude,Longitude,Census_Tract
0,79220,2020-01-01,0,120,Robbery,Burglary/Robbery,1,12D60,"Residence, Home (Includes Apartment)",162,EL CAMINO REAL,<NA>,Houston,TX,77062,"16302 EL CAMINO REAL , Houston, TX",16302+EL+CAMINO+REAL+,29.560020,-95.125244,340701
1,59342520,2020-01-01,0,220,"Burglary, Breaking and Entering",Burglary/Robbery,1,14D40,"Residence, Home (Includes Apartment)",1,MARTIN LUTHER KING,BLVD,Houston,TX,77048,"12000 MARTIN LUTHER KING BLVD, Houston, TX",12000+MARTIN+LUTHER+KING+BLVD,0.000000,0.000000,331604
2,123324720,2020-01-01,0,220,"Burglary, Breaking and Entering",Burglary/Robbery,1,4F10,Restaurant,94,KATY,FWY,Houston,TX,77055,"9440 KATY FWY, Houston, TX",9440+KATY+FWY,29.785149,-95.531461,522301
3,233120,2020-01-01,0,240,Motor vehicle theft,Theft,1,16E30,"Parking Lot, Garage",14711,MAIN,ST,Houston,TX,77085,"14711 MAIN ST, Houston, TX",14711+MAIN+ST,29.676383,-95.428505,0
4,240920,2020-01-01,0,240,Motor vehicle theft,Theft,1,20G30,"Residence, Home (Includes Apartment)",,SHADOWBRIAR,DR,Houston,TX,77082,"3030 SHADOWBRIAR DR, Houston, TX",3030+SHADOWBRIAR+DR,29.731948,-95.599466,452002
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
354130,133031021,2021-09-30,23,290,"Destruction, damage, vandalism",Vandalism,1,7C10,"Residence, Home (Includes Apartment)",4417,NICHOLS,ST,Houston,TX,77020,"4417 NICHOLS ST, Houston, TX",4417+NICHOLS+ST,29.781080,-95.326351,211301
354131,133300021,2021-09-30,23,290,"Destruction, damage, vandalism",Vandalism,1,19G10,"Parking Lot, Garage",6,BEECHNUT,ST,Houston,TX,77072,"10630 BEECHNUT ST, Houston, TX",10630+BEECHNUT+ST,29.689024,-95.604058,453100
354132,133300021,2021-09-30,23,23F,Theft from motor vehicle,Theft,1,19G10,"Parking Lot, Garage",6,BEECHNUT,ST,Houston,TX,77072,"10630 BEECHNUT ST, Houston, TX",10630+BEECHNUT+ST,29.689024,-95.604058,453100
354133,134942021,2021-09-30,23,290,"Destruction, damage, vandalism",Vandalism,1,15E30,"Residence, Home (Includes Apartment)",7171,BUFFALO SPEEDWAY,<NA>,Houston,TX,77025,"7171 BUFFALO SPEEDWAY , Houston, TX",7171+BUFFALO+SPEEDWAY+,29.702431,-95.427477,413203
354134,136362221,2021-09-30,23,240,Motor vehicle theft,Theft,1,22B20,"Residence, Home (Includes Apartment)",0,GREENS,RD,Houston,TX,77060,"400 GREENS RD, Houston, TX",400+GREENS+RD,29.950418,-95.406558,240102

# #Create a DF called Criminal_Activity for SQL

In [46]:
criminal_activity_df = crime_df[["Incident","Date","Hour","Offense_Type","Offense_Grouped","Beat","Premise","Street_No","Street_Name","Street_Type","Full_Address" ]]


criminal_activity_df["ID"] = criminal_activity_df.index + 1
criminal_activity_df

<ipython-input-46-3e65016b17a0>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  criminal_activity_df["ID"] = criminal_activity_df.index + 1

,Incident,Date,Hour,Offense_Type,Offense_Grouped,Beat,Premise,Street_No,Street_Name,Street_Type,Full_Address,ID
0,79220,2020-01-01,0,Robbery,Burglary/Robbery,12D60,"Residence, Home (Includes Apartment)",16302.0,EL CAMINO REAL,<NA>,"16302 EL CAMINO REAL , Houston, TX",1
1,59342520,2020-01-01,0,"Burglary, Breaking and Entering",Burglary/Robbery,14D40,"Residence, Home (Includes Apartment)",12000.0,MARTIN LUTHER KING,BLVD,"12000 MARTIN LUTHER KING BLVD, Houston, TX",2
2,123324720,2020-01-01,0,"Burglary, Breaking and Entering",Burglary/Robbery,4F10,Restaurant,9440.0,KATY,FWY,"9440 KATY FWY, Houston, TX",3
3,233120,2020-01-01,0,Motor vehicle theft,Theft,16E30,"Parking Lot, Garage",14711.0,MAIN,ST,"14711 MAIN ST, Houston, TX",4
4,240920,2020-01-01,0,Motor vehicle theft,Theft,20G30,"Residence, Home (Includes Apartment)",3030.0,SHADOWBRIAR,DR,"3030 SHADOWBRIAR DR, Houston, TX",5
...,...,...,...,...,...,...,...,...,...,...,...,...
354130,133031021,2021-09-30,23,"Destruction, damage, vandalism",Vandalism,7C10,"Residence, Home (Includes Apartment)",4417.0,NICHOLS,ST,"4417 NICHOLS ST, Houston, TX",354131
354131,133300021,2021-09-30,23,"Destruction, damage, vandalism",Vandalism,19G10,"Parking Lot, Garage",10630.0,BEECHNUT,ST,"10630 BEECHNUT ST, Houston, TX",354132
354132,133300021,2021-09-30,23,Theft from motor vehicle,Theft,19G10,"Parking Lot, Garage",10630.0,BEECHNUT,ST,"10630 BEECHNUT ST, Houston, TX",354133
354133,134942021,2021-09-30,23,"Destruction, damage, vandalism",Vandalism,15E30,"Residence, Home (Includes Apartment)",7171.0,BUFFALO SPEEDWAY,<NA>,"7171 BUFFALO SPEEDWAY , Houston, TX",354134
354134,136362221,2021-09-30,23,Motor vehicle theft,Theft,22B20,"Residence, Home (Includes Apartment)",400.0,GREENS,RD,"400 GREENS RD, Houston, TX",354135

In [47]:
criminal_activity_df['Full_Address'] = criminal_activity_df['Full_Address'].replace(', Houston, TX', '', regex=True)
criminal_activity_df

<ipython-input-47-b9a077aa0c07>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  criminal_activity_df['Full_Address'] = criminal_activity_df['Full_Address'].replace(', Houston, TX', '', regex=True)

,Incident,Date,Hour,Offense_Type,Offense_Grouped,Beat,Premise,Street_No,Street_Name,Street_Type,Full_Address,ID
0,79220,2020-01-01,0,Robbery,Burglary/Robbery,12D60,"Residence, Home (Includes Apartment)",16302.0,EL CAMINO REAL,<NA>,16302 EL CAMINO REAL,1
1,59342520,2020-01-01,0,"Burglary, Breaking and Entering",Burglary/Robbery,14D40,"Residence, Home (Includes Apartment)",12000.0,MARTIN LUTHER KING,BLVD,12000 MARTIN LUTHER KING BLVD,2
2,123324720,2020-01-01,0,"Burglary, Breaking and Entering",Burglary/Robbery,4F10,Restaurant,9440.0,KATY,FWY,9440 KATY FWY,3
3,233120,2020-01-01,0,Motor vehicle theft,Theft,16E30,"Parking Lot, Garage",14711.0,MAIN,ST,14711 MAIN ST,4
4,240920,2020-01-01,0,Motor vehicle theft,Theft,20G30,"Residence, Home (Includes Apartment)",3030.0,SHADOWBRIAR,DR,3030 SHADOWBRIAR DR,5
...,...,...,...,...,...,...,...,...,...,...,...,...
354130,133031021,2021-09-30,23,"Destruction, damage, vandalism",Vandalism,7C10,"Residence, Home (Includes Apartment)",4417.0,NICHOLS,ST,4417 NICHOLS ST,354131
354131,133300021,2021-09-30,23,"Destruction, damage, vandalism",Vandalism,19G10,"Parking Lot, Garage",10630.0,BEECHNUT,ST,10630 BEECHNUT ST,354132
354132,133300021,2021-09-30,23,Theft from motor vehicle,Theft,19G10,"Parking Lot, Garage",10630.0,BEECHNUT,ST,10630 BEECHNUT ST,354133
354133,134942021,2021-09-30,23,"Destruction, damage, vandalism",Vandalism,15E30,"Residence, Home (Includes Apartment)",7171.0,BUFFALO SPEEDWAY,<NA>,7171 BUFFALO SPEEDWAY,354134
354134,136362221,2021-09-30,23,Motor vehicle theft,Theft,22B20,"Residence, Home (Includes Apartment)",400.0,GREENS,RD,400 GREENS RD,354135

In [48]:
criminal_activity_df.dtypes

Incident                   string
Date               datetime64[ns]
Hour                        int64
Offense_Type               string
Offense_Grouped            string
Beat                       string
Premise                    string
Street_No                  string
Street_Name                string
Street_Type                string
Full_Address               string
ID                          int64
dtype: object

<ipython-input-29-9acf3ea3b05d>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  criminal_activity_df["ID"] = criminal_activity_df.index + 1

,Incident,Date,Hour,Offense_Type,Offense_Grouped,Beat,Premise,Street_No,Street_Name,Street_Type,ID
0,79220,2020-01-01,0,Robbery,Burglary/Robbery,12D60,"Residence, Home (Includes Apartment)",16302.0,EL CAMINO REAL,NaN,1
1,59342520,2020-01-01,0,"Burglary, Breaking and Entering",Burglary/Robbery,14D40,"Residence, Home (Includes Apartment)",12000.0,MARTIN LUTHER KING,BLVD,2
2,123324720,2020-01-01,0,"Burglary, Breaking and Entering",Burglary/Robbery,4F10,Restaurant,9440.0,KATY,FWY,3
3,233120,2020-01-01,0,Motor vehicle theft,Theft,16E30,"Parking Lot, Garage",14711.0,MAIN,ST,4
4,240920,2020-01-01,0,Motor vehicle theft,Theft,20G30,"Residence, Home (Includes Apartment)",3030.0,SHADOWBRIAR,DR,5
...,...,...,...,...,...,...,...,...,...,...,...
354130,133031021,2021-09-30,23,"Destruction, damage, vandalism",Vandalism,7C10,"Residence, Home (Includes Apartment)",4417.0,NICHOLS,ST,354131
354131,133300021,2021-09-30,23,"Destruction, damage, vandalism",Vandalism,19G10,"Parking Lot, Garage",10630.0,BEECHNUT,ST,354132
354132,133300021,2021-09-30,23,Theft from motor vehicle,Theft,19G10,"Parking Lot, Garage",10630.0,BEECHNUT,ST,354133
354133,134942021,2021-09-30,23,"Destruction, damage, vandalism",Vandalism,15E30,"Residence, Home (Includes Apartment)",7171.0,BUFFALO SPEEDWAY,NaN,354134
354134,136362221,2021-09-30,23,Motor vehicle theft,Theft,22B20,"Residence, Home (Includes Apartment)",400.0,GREENS,RD,354135

In [49]:
criminal_activity_df.to_csv('criminal_activity_df.csv', index=False)

# #Population data  SQL cleanup

In [2]:
population_df = pd.read_csv("5_Population_Data.csv")
population_df

,Zipcode,Population,Population Density,Housing Units,Median Home Value,Occupied_Housing_Units,Median_Household_Income,Gender_Male,Gender_Female,White,...,Single_Guardian,Singles,Single_With_Roomate,Owned_With_Mortgage,Owned_No_Mortgage,Renter,Vacant,Full_Time,Part_Time,Unemployed
0,77062,"25,152","4,637","9,910","$160,100","9,408","$87,960","12,495","12,657","18,848",...,"1,288","1,873",369,"5,239","2,275","1,894",502,"9,664","4,927","5,915"
1,77048,"15,294","1,380","6,501","$81,200","5,223","$36,818","7,047","8,247","1,740",...,"2,076","1,171",224,"2,057","1,211","1,955","1,278","4,335","2,468","5,484"
2,77055,"41,989","5,023","16,005","$230,300","14,152","$46,987","21,904","20,085","27,708",...,"3,178","3,446","1,219","3,983","2,399","7,770","1,853","14,966","7,466","9,677"
3,77085,"16,074","3,036","4,857","$106,600","4,571","$49,466","7,879","8,195","5,886",...,"1,242",726,167,"2,636",729,"1,206",286,"5,642","2,191","3,784"
4,77082,"49,900","3,975","23,058","$124,000","20,374","$50,294","23,719","26,181","19,857",...,"4,631","6,816","1,439","6,304","1,484","12,586","2,684","20,248","8,809","10,447"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
169,77318,"14,281",372,"6,780","$166,100","5,640","$78,194","7,017","7,264","12,686",...,819,"1,160",271,"3,009","1,561","1,070","1,140","4,888","2,505","3,594"
170,77550,"23,043","3,069","14,615","$117,200","9,972","$32,447","11,696","11,347","12,056",...,"2,244","3,938","1,001","2,141","2,063","5,768","4,643","6,617","5,634","6,421"
171,77372,"12,164",234,"4,544","$75,800","4,094","$44,896","6,015","6,149","10,766",...,806,720,200,"1,701","1,616",777,450,"3,616","2,116","3,622"
172,77485,"4,054",49,"1,769","$135,800","1,535","$60,900","2,029","2,025","3,063",...,221,341,71,637,572,326,234,"1,507",367,"1,201"
173,77010,366,"2,965",471,"$526,300",249,"$250,001",206,160,305,...,4,149,25,12,9,228,222,372,50,114

In [3]:
#Clean up the headers
population_df = population_df.rename(columns = {  "Zipcode": "Zip_Code", 
                                                  "Population Density": "Population_Density",
                                                  "Housing Units": "Housing_Units",
                                                  "Median Home Value": "Median_Home_Value",
                                                  "White":"Race_White",
                                                  "Black":"Race_Black",
                                                  "Indian":"Race_Indian",
                                                  "Asian":"Race_Asian",
                                                  "Hawaiian":"Race_Hawaiian",
                                                  "Other":"Race_Other",
                                                  "Mixed":"Race_Mixed"
                                               }
                                    )
    
population_df.head() 
population_df["ID"] = population_df.index + 1
population_df

,Zip_Code,Population,Population_Density,Housing_Units,Median_Home_Value,Occupied_Housing_Units,Median_Household_Income,Gender_Male,Gender_Female,Race_White,...,Singles,Single_With_Roomate,Owned_With_Mortgage,Owned_No_Mortgage,Renter,Vacant,Full_Time,Part_Time,Unemployed,ID
0,77062,"25,152","4,637","9,910","$160,100","9,408","$87,960","12,495","12,657","18,848",...,"1,873",369,"5,239","2,275","1,894",502,"9,664","4,927","5,915",1
1,77048,"15,294","1,380","6,501","$81,200","5,223","$36,818","7,047","8,247","1,740",...,"1,171",224,"2,057","1,211","1,955","1,278","4,335","2,468","5,484",2
2,77055,"41,989","5,023","16,005","$230,300","14,152","$46,987","21,904","20,085","27,708",...,"3,446","1,219","3,983","2,399","7,770","1,853","14,966","7,466","9,677",3
3,77085,"16,074","3,036","4,857","$106,600","4,571","$49,466","7,879","8,195","5,886",...,726,167,"2,636",729,"1,206",286,"5,642","2,191","3,784",4
4,77082,"49,900","3,975","23,058","$124,000","20,374","$50,294","23,719","26,181","19,857",...,"6,816","1,439","6,304","1,484","12,586","2,684","20,248","8,809","10,447",5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
169,77318,"14,281",372,"6,780","$166,100","5,640","$78,194","7,017","7,264","12,686",...,"1,160",271,"3,009","1,561","1,070","1,140","4,888","2,505","3,594",170
170,77550,"23,043","3,069","14,615","$117,200","9,972","$32,447","11,696","11,347","12,056",...,"3,938","1,001","2,141","2,063","5,768","4,643","6,617","5,634","6,421",171
171,77372,"12,164",234,"4,544","$75,800","4,094","$44,896","6,015","6,149","10,766",...,720,200,"1,701","1,616",777,450,"3,616","2,116","3,622",172
172,77485,"4,054",49,"1,769","$135,800","1,535","$60,900","2,029","2,025","3,063",...,341,71,637,572,326,234,"1,507",367,"1,201",173
173,77010,366,"2,965",471,"$526,300",249,"$250,001",206,160,305,...,149,25,12,9,228,222,372,50,114,174

In [4]:
population_df.dtypes

Zip_Code                    int64
Population                 object
Population_Density         object
Housing_Units              object
Median_Home_Value          object
Occupied_Housing_Units     object
Median_Household_Income    object
Gender_Male                object
Gender_Female              object
Race_White                 object
Race_Black                 object
Race_Indian                object
Race_Asian                 object
Race_Hawaiian               int64
Race_Other                 object
Race_Mixed                 object
Whole_Family               object
Single_Guardian            object
Singles                    object
Single_With_Roomate        object
Owned_With_Mortgage        object
Owned_No_Mortgage          object
Renter                     object
Vacant                     object
Full_Time                  object
Part_Time                  object
Unemployed                 object
ID                          int64
dtype: object

In [5]:
population_df.to_csv('population_df.csv', index=False)

# #Create a new DF for Tracts

In [55]:
tract_zip_lat_long_df = crime_df[["Full_Address","Census_Tract","Zip_Code","Latitude","Longitude"]] 
tract_zip_lat_long_df['Full_Address'] = crime_df['Full_Address'].replace(', Houston, TX', '', regex=True)



tract_zip_lat_long_df

<ipython-input-55-435e7a4851a2>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tract_zip_lat_long_df['Full_Address'] = crime_df['Full_Address'].replace(', Houston, TX', '', regex=True)

,Full_Address,Census_Tract,Zip_Code,Latitude,Longitude
0,16302 EL CAMINO REAL,340701.0,77062,29.560020,-95.125244
1,12000 MARTIN LUTHER KING BLVD,331604.0,77048,NaN,NaN
2,9440 KATY FWY,522301.0,77055,29.785149,-95.531461
3,14711 MAIN ST,<NA>,77085,29.676383,-95.428505
4,3030 SHADOWBRIAR DR,452002.0,77082,29.731948,-95.599466
...,...,...,...,...,...
354130,4417 NICHOLS ST,211301.0,77020,29.781080,-95.326351
354131,10630 BEECHNUT ST,453100.0,77072,29.689024,-95.604058
354132,10630 BEECHNUT ST,453100.0,77072,29.689024,-95.604058
354133,7171 BUFFALO SPEEDWAY,413203.0,77025,29.702431,-95.427477
354134,400 GREENS RD,240102.0,77060,29.950418,-95.406558

In [56]:
tract_zip_lat_long_df["ID"] = tract_zip_lat_long_df.index + 1
tract_zip_lat_long_df

<ipython-input-56-4a7f9520681d>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tract_zip_lat_long_df["ID"] = tract_zip_lat_long_df.index + 1

,Full_Address,Census_Tract,Zip_Code,Latitude,Longitude,ID
0,16302 EL CAMINO REAL,340701.0,77062,29.560020,-95.125244,1
1,12000 MARTIN LUTHER KING BLVD,331604.0,77048,NaN,NaN,2
2,9440 KATY FWY,522301.0,77055,29.785149,-95.531461,3
3,14711 MAIN ST,<NA>,77085,29.676383,-95.428505,4
4,3030 SHADOWBRIAR DR,452002.0,77082,29.731948,-95.599466,5
...,...,...,...,...,...,...
354130,4417 NICHOLS ST,211301.0,77020,29.781080,-95.326351,354131
354131,10630 BEECHNUT ST,453100.0,77072,29.689024,-95.604058,354132
354132,10630 BEECHNUT ST,453100.0,77072,29.689024,-95.604058,354133
354133,7171 BUFFALO SPEEDWAY,413203.0,77025,29.702431,-95.427477,354134
354134,400 GREENS RD,240102.0,77060,29.950418,-95.406558,354135

In [60]:
tract_zip_lat_long_df['Census_Tract'] = tract_zip_lat_long_df['Census_Tract'].astype(int)
tract_zip_lat_long_df

ValueError: invalid literal for int() with base 10: '340701.0'

In [57]:
tract_zip_lat_long_df.to_csv('location_df.csv', index=False)